server:
  port: 8080


#服务的名称
spring:
  application:
    name: zuul-service



#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

#/order-service/api/v1/order/save?user_id=2&product_id=1
#自定义路由映射
zuul:
  routes:
    zuul-service: /service-zuul/**
    common-service: /service-common/**
    order-service: /service-order/**
    product-service: /service-product/**
    business-service: /service-business/**

  #统一入口为上面的配置，其他入口忽略
  ignored-patterns: /*-service/**
  #忽略整个服务，对外提供接口
  ignored-services: order-service