#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

server:
  port: 9001

#服务的名称
spring:
  application:
    name: product-service


#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@//127.0.0.1:1521/orcl
#    username: etsrfk
#    password: etsrfk
#
#    redis:
#      database: 0
#      host: 127.0.0.1
#      port: 6379

#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: cty123456
#    database: 0
#    lettuce:
#      pool:
#        max-wait: 100000
#        max-idle: 10
#        max-active: 100
#    timeout: 5000




#mybatis配置
#mybatis:
#  config-location: classpath:mybatis-config.xml
#  type-aliases-package: com.ccty.service.product.entity           # 所有Entity别名类所在包
#  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:logback-product.xml

