#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

server:
  port: 9005

#服务的名称
spring:
  application:
    name: business-service

    #指定从哪个配置中心读取
    cloud:
      config:
        uri: http://localhost:5001   #配置服务中心的uri
        name: config-business     #配置文件名称的前缀
        enabled: true    #开启配置
        profile: dev   #版本
        label: ""     #git配置的分支信息，如：master

name: false

