#服务名称
server:
  port: 6001

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

#配置当前服务的名称
spring:
  application:
    name: config-server    #向注册中心进行注册的服务名
  profiles:
    active: native #设置为本地启动的方式，而不是通过git

  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config/   # 配置文件所在目录





